### ISSUE TITLE
Sitenin karışıklığı

### ISSUE THREAD

**Issue by 2013dogumeymen** [GokturkTalha/guvendekal.org#9]
sitede ne nerede belli değil sanki bir makalenin bölümleri gibi tasarlanmış site ayrıca daha fazla eklendikçe daha karmaşık hale gelir

![Örnek](https://github.com/user-attachments/assets/4e7d9394-e6da-4c45-ba09-417cb9aec861)

**Comment by GokturkTalha** [comment]
Site klasik dökümantasyon siteleri konseptindedir, site daha yeni olduğu için kategoriler ve menüler karmaşık/yanlış gelebilir.

Zamanla oturacak ve karmaşık gelmeyecek bir hâle gelecektir.
